version: '3'

services:
    web:
        image: cure-back-image:1.0
        container_name: cure-back-container
        build: .
        command: ./entrypoint.sh
        stdin_open: true
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
