version: '3'

services:
    web:
        user: root
        build: .
        command: ./entrypoint.sh
        stdin_open: true
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
